services:
  - type: web
    name: anomaly-detector
    env: docker
    plan: free
    autoDeploy: true
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    envVars:
      - key: FLASK_DEBUG
        value: false
